name: test
on:
  push:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test=hello"
      - run: echo "::debug::Set the Octocat variable"
      - run: echo "::workflow-command parameter1={data},parameter2={data}::{command value}"
